// Global Metrics
export const FETCH_LATEST_GLOBAL_METRICS_BEGIN = 'FETCH_LATEST_GLOBAL_METRICS_BEGIN'
export const FETCH_LATEST_GLOBAL_METRICS_SUCCESS = 'FETCH_LATEST_GLOBAL_METRICS_SUCCESS'
export const FETCH_LATEST_GLOBAL_METRICS_FAILURE = 'FETCH_LATEST_GLOBAL_METRICS_FAILURE'

// Crypto currencies
export const FETCH_CRYPT_CURRENCIES_BEGIN = 'FETCH_CRYPT_CURRENCIES_BEGIN'
export const FETCH_CRYPT_CURRENCIES_SUCCESS = 'FETCH_CRYPT_CURRENCIES_SUCCESS'
export const FETCH_CRYPT_CURRENCIES_FAILURE = 'FETCH_CRYPT_CURRENCIES_FAILURE'
